

package carrera;


import javax.swing.JLabel;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author israel
 */


public class frmCarrera extends javax.swing.JFrame {
    //int contador = 0;
    /**
     * Creates new form frmCarrera
     */
    public frmCarrera() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Carrera De Autos");
    }
    
    public JLabel getPrimerAuto (){
        return primer_auto;
    }
    
    public JLabel getSegundoAuto (){
        return segundo_auto;
    }
    
    public JLabel getBarrera(){
        return barrera;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaTitulo = new javax.swing.JLabel();
        botoniniciar = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        primer_auto = new javax.swing.JLabel();
        segundo_auto = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JButton();
        barrera = new javax.swing.JLabel();
        fondoImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTitulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        etiquetaTitulo.setForeground(new java.awt.Color(0, 0, 255));
        etiquetaTitulo.setText("Carrera de Autos");
        getContentPane().add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 460, 66));

        botoniniciar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        botoniniciar.setForeground(new java.awt.Color(0, 51, 255));
        botoniniciar.setText("Iniciar ");
        botoniniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoniniciarActionPerformed(evt);
            }
        });
        getContentPane().add(botoniniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 140, 40));

        btnTerminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        btnTerminar.setForeground(new java.awt.Color(0, 51, 255));
        btnTerminar.setText("Teminar");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 160, 40));

        primer_auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/auto_azul.png"))); // NOI18N
        getContentPane().add(primer_auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        segundo_auto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carro_rojo.png"))); // NOI18N
        getContentPane().add(segundo_auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        btnReiniciar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        btnReiniciar.setForeground(new java.awt.Color(0, 51, 255));
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnReiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 140, 40));

        barrera.setBackground(new java.awt.Color(255, 0, 0));
        barrera.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        barrera.setForeground(new java.awt.Color(0, 0, 255));
        barrera.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        barrera.setText("FIN");
        barrera.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        barrera.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        barrera.setOpaque(true);
        barrera.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(barrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 50, 390));

        fondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrera_modificada1.jpg"))); // NOI18N
        fondoImagen.setToolTipText("");
        fondoImagen.setMaximumSize(new java.awt.Dimension(1200, 623));
        getContentPane().add(fondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 860, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoniniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoniniciarActionPerformed
        
        primer_auto.setLocation(0,primer_auto.getLocation().y);
        segundo_auto.setLocation(0,segundo_auto.getLocation().y);
        
        Carrera auto1 = new  Carrera(primer_auto , this);
        Carrera auto2 = new Carrera(segundo_auto, this);
        
        auto1.start();
        auto2.start();        
    }//GEN-LAST:event_botoniniciarActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        primer_auto.setLocation(0,getLocation().y);
        segundo_auto.setLocation(0,getLocation().x);
    }//GEN-LAST:event_btnReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarrera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");//texturas color
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarrera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barrera;
    private javax.swing.JButton botoniniciar;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel fondoImagen;
    private javax.swing.JLabel primer_auto;
    private javax.swing.JLabel segundo_auto;
    // End of variables declaration//GEN-END:variables
}
